(() => {
  const id=new URLSearchParams(location.search).get('id')||'violette-03';
  if(id==='violette-03') return;
  const P=window.VIOLET_PERSONALIZATION; const DATA=window.VIOLET_DATA||{products:[]};
  const product=DATA.products.find(item=>item.id===id)||DATA.products[0]; if(!product) return;
  const host=document.querySelector('[data-static-violette-pdp]'); if(!host) return;
  const meta=P?.metaFor(product.id)||{moods:[],projection:'balanced',sample:false}; const notes=product.notes||{};
  const money=n=>`${new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(Number(n||0))} €`;
  document.title=`${product.name} · ${product.brand} · Violet Parfumerie`;
  host.innerHTML=`<div class="explore-pdp-intro"><div class="v4-pdp-media"><div class="v4-pdp-media-index"><span>V.11 / OBJECT STUDY</span><span>${product.family||'Fine fragrance'}</span></div><div class="v5-gallery"><figure class="v5-gallery-tile v5-gallery-main"><img src="${product.image}" fetchpriority="high" alt="${product.name} by ${product.brand}"><figcaption class="v5-media-caption">Object view</figcaption></figure><figure class="v5-gallery-tile"><img src="assets/media/editorial-03.jpg" loading="lazy" alt="Editorial material study"><figcaption class="v5-media-caption">Material study</figcaption></figure><figure class="v5-gallery-tile"><img src="assets/media/editorial-07.jpg" loading="lazy" alt="Editorial atmosphere"><figcaption class="v5-media-caption">Atmosphere</figcaption></figure></div><div class="v4-pdp-media-foot"><span>${product.brand}</span><span>${product.concentration||''} · ${product.size||''}</span></div></div><aside class="v4-buying-desk"><div class="v4-buying-index"><span>VIOLET OBJECT</span><span>${meta.sample?'TRY FIRST':'VIOLET EDIT'}</span></div><a class="v4-pdp-house" href="houses.html">${product.brand}</a><h1>${product.name}</h1><p class="v4-pdp-character">${product.description}</p><div class="v4-pdp-format">${product.concentration||''} · ${product.size||''} · ${product.family||''}</div><div class="v4-pdp-price"><strong>${money(product.price)}</strong><span>Prototype inventory</span></div><div class="v4-pdp-actions"><button class="btn btn-primary" type="button" data-v4-add-bottle="${product.id}">Add full bottle</button>${meta.sample?`<button class="btn btn-secondary" type="button" data-v4-add-sample="${product.id}">Add to trial trio</button>`:'<a class="btn btn-secondary" href="discovery.html">Explore discovery</a>'}</div><p class="v4-reality-note">Browser-local prototype commerce. Fictional houses and inventory; no fulfilment is connected.</p></aside></div><section class="v4-pdp-story"><figure class="v5-story-media"><img src="assets/media/editorial-04.jpg" loading="lazy" alt="Editorial scent atmosphere"><figcaption class="v5-media-caption">Atmosphere / editorial reference</figcaption></figure><div class="v5-story-copy"><div class="v4-pdp-story-lead"><span class="v4-kicker">01 / THE SCENT</span><h2>${product.description}</h2></div><div class="v4-note-table"><div><span>Top</span><strong>${notes.top||'—'}</strong></div><div><span>Heart</span><strong>${notes.heart||'—'}</strong></div><div><span>Base</span><strong>${notes.base||'—'}</strong></div></div></div></section>`;
  host.querySelector('[data-v4-add-bottle]')?.addEventListener('click',event=>{P?.addToCart(product.id,1);event.currentTarget.textContent='Added to bag ✓';});
  host.querySelector('[data-v4-add-sample]')?.addEventListener('click',event=>{const trio=P?.getTrio()||[];if(!trio.includes(product.id)&&trio.length<3)P.setTrio([...trio,product.id]);event.currentTarget.textContent=trio.length>=3&&!trio.includes(product.id)?'Trio full · review':'Added to trio ✓';});
})();
