"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useCart } from "@/components/cart-store";
import { formatVND } from "@/lib/data";

export default function CheckoutPage() {
  const { items, subtotal, clear } = useCart();
  const [done, setDone] = useState(false);
  const shipping = items.length ? 30000 : 0;
  const shippingDiscount = subtotal >= 1000000 ? shipping : 0;
  const total = subtotal + shipping - shippingDiscount;
  const submit = (event: FormEvent) => { event.preventDefault(); setDone(true); clear(); window.scrollTo({ top: 0, behavior: "smooth" }); };
  if (done) return <main className="page-shell"><div className="container"><div className="checkout-success"><b>✓</b><h1>Đơn hàng đã được ghi nhận</h1><p>Mã demo: VLT-090826-1284 · Bạn có thể dùng màn hình này để review UX order-success.</p><Link className="button primary" href="/">Về trang chủ</Link></div></div></main>;
  if (!items.length) return <main className="page-shell"><div className="container"><div className="empty-state"><h1>Chưa có sản phẩm để thanh toán</h1><Link className="button primary" href="/">Quay lại mua sắm</Link></div></div></main>;
  return <main className="page-shell"><div className="container"><div className="page-title"><div><span className="eyebrow">SECURE CHECKOUT</span><h1>Thanh toán</h1><p>Không banner, không recommendation — chỉ những gì cần để hoàn tất đơn.</p></div></div><form className="checkout-layout" onSubmit={submit}><div className="checkout-form"><section className="checkout-section"><h2>1. Thông tin nhận hàng</h2><div className="field-grid"><div className="field"><label>Họ và tên</label><input required placeholder="Nguyễn Văn A"/></div><div className="field"><label>Số điện thoại</label><input required placeholder="09xx xxx xxx"/></div><div className="field full"><label>Địa chỉ</label><input required placeholder="Số nhà, tên đường, phường/xã"/></div><div className="field"><label>Thành phố</label><select defaultValue="hcm"><option value="hcm">TP. Hồ Chí Minh</option><option>Hà Nội</option><option>Đà Nẵng</option></select></div><div className="field"><label>Quận/Huyện</label><input required placeholder="Quận 1"/></div></div></section><section className="checkout-section"><h2>2. Phương thức giao hàng</h2><label className="choice"><input type="radio" name="ship" defaultChecked/><div><strong>Giao tiêu chuẩn · {formatVND(0)}</strong><p>Dự kiến 10–11/09 · Freeship đã được áp dụng</p></div></label><label className="choice"><input type="radio" name="ship"/><div><strong>Giao ưu tiên · {formatVND(39000)}</strong><p>Nhận sớm nhất vào ngày mai với sản phẩm đủ điều kiện</p></div></label></section><section className="checkout-section"><h2>3. Thanh toán</h2><label className="choice"><input type="radio" name="pay" defaultChecked/><div><strong>Thanh toán khi nhận hàng</strong><p>Kiểm tra trạng thái đơn trước khi thanh toán.</p></div></label><label className="choice"><input type="radio" name="pay"/><div><strong>Thẻ / Ví điện tử</strong><p>Prototype UI — chưa kết nối payment provider.</p></div></label></section></div><aside className="summary-card"><h2>Đơn hàng của bạn</h2>{items.map(line => <div className="summary-row" key={line.product.id}><span>{line.product.name} × {line.quantity}</span><span>{formatVND(line.product.price * line.quantity)}</span></div>)}<div className="summary-row"><span>Vận chuyển</span><span>{formatVND(shipping)}</span></div><div className="summary-row"><span>Freeship</span><span>-{formatVND(shippingDiscount)}</span></div><div className="summary-row total"><strong>Tổng thanh toán</strong><strong>{formatVND(total)}</strong></div><button className="button primary" type="submit">Đặt hàng</button><p className="summary-note">Bằng việc đặt hàng, bạn xác nhận thông tin và đồng ý với chính sách của Violet Marketplace.</p></aside></form></div></main>;
}
