import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { chromium } from 'playwright';

const out=path.resolve(process.argv[2]||'artifacts/mobile-discovery-qa');fs.mkdirSync(out,{recursive:true});
const port=4181,base=`http://127.0.0.1:${port}`;const server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1'],{cwd:process.cwd(),stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function wait(){for(let i=0;i<50;i++){try{if((await fetch(`${base}/index.html`)).ok)return}catch{}await sleep(200)}throw new Error('server not ready')}
const report={status:'passed',viewport:{width:390,height:844},tasks:[],pages:[],issues:[]};const issue=(page,severity,code,message)=>report.issues.push({page,severity,code,message});
async function settle(page){await page.waitForLoadState('networkidle');await page.waitForTimeout(180)}
async function inspect(page,name){const m=await page.evaluate(()=>{const visible=e=>{if(!e)return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none'};const touch=[...document.querySelectorAll('button,.btn,.portrait-option,.mobile-nav a')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return {label:(e.textContent||e.getAttribute('aria-label')||'').trim().slice(0,80),w:Math.round(r.width),h:Math.round(r.height)}});return {scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,h1:document.querySelectorAll('h1').length,broken:[...document.images].filter(i=>visible(i)&&i.complete&&i.naturalWidth===0).map(i=>i.src),smallTouch:touch.filter(x=>x.w<42||x.h<42).slice(0,12),nav:visible(document.querySelector('.mobile-nav'))};});if(m.scrollWidth>m.clientWidth+2)issue(name,'P0','overflow',`${m.scrollWidth}>${m.clientWidth}`);if(m.h1!==1)issue(name,'P1','heading',`expected 1 h1, got ${m.h1}`);if(m.broken.length)issue(name,'P0','broken-media',m.broken.join(' | '));if(m.smallTouch.length)issue(name,'P1','touch-target',JSON.stringify(m.smallTouch));if(!m.nav&&!['seller','admin'].includes(name))issue(name,'P1','mobile-nav','mobile journey nav not visible');await page.screenshot({path:path.join(out,`${name}-390.png`),fullPage:true});report.pages.push({name,...m});return m}
async function task(name,fn){try{await fn();report.tasks.push({name,status:'passed'})}catch(error){report.tasks.push({name,status:'failed',error:String(error)});issue(name,'P0','task-failed',String(error))}}

await wait();const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,colorScheme:'light',hasTouch:true,isMobile:true});

await task('1-find-by-mood',async()=>{const page=await context.newPage();await page.goto(`${base}/search.html?mood=warm`);await settle(page);const text=await page.locator('body').innerText();if(!/Warm|warm/.test(text))throw new Error('warm mood context not visible');if(await page.locator('[data-results] .v4-object-card').count()<1)throw new Error('no mood results');await inspect(page,'library-mood');await page.close()});

let firstRecommendation='';
await task('2-explain-recommendation',async()=>{const page=await context.newPage();await page.goto(`${base}/finder.html`);await settle(page);const choose=async(value)=>{const b=page.locator(`[data-value="${value}"]`);await b.click();await page.locator('[data-next]').click()};await choose('floral');await choose('soft');await page.locator('[data-value="gourmand"]').click();await page.locator('[data-next]').click();await choose('1');await choose('1');await choose('quiet');await choose('evening');await choose('mild');await page.locator('[data-text-answer]').fill('iris, tea');await page.locator('[data-next]').click();await page.waitForSelector('.portrait-results');if(await page.getByText('Why this matches you',{exact:true}).count()<1)throw new Error('why-match explanation missing');if(!/not AI predictions/i.test(await page.locator('.portrait-results').innerText()))throw new Error('rule-based truth label missing');firstRecommendation=await page.locator('.portrait-result').first().locator('h3').innerText();await inspect(page,'portrait-results');await page.close()});

await task('3-distinguish-bottle-sample',async()=>{const page=await context.newPage();await page.goto(`${base}/product.html?id=violette-03`);await settle(page);if(await page.getByText('Why this matches you',{exact:true}).count()<1)throw new Error('PDP match explanation missing');const body=await page.locator('.v4-buying-desk').innerText();if(!/Full bottle/i.test(body)||!/Trial sample/i.test(body))throw new Error('full bottle and trial sample not clearly distinguished');await inspect(page,'pdp-profile');await page.close()});

await task('4-build-balanced-trio',async()=>{const page=await context.newPage();await page.goto(`${base}/discovery.html`);await settle(page);await page.evaluate(()=>localStorage.removeItem('violet-discovery-trio-v1'));await page.reload();await settle(page);const choices=page.locator('[data-v7-sample]');for(let i=0;i<3;i++)await choices.nth(i).click();if(await page.locator('.v7-trio-slot:not(.is-empty)').count()!==3)throw new Error('trio did not reach 3/3');if(await page.locator('.v7-balance').count()!==1)throw new Error('balance summary missing');if(await page.locator('[data-add-trio-bag]:not([disabled])').count()!==1)throw new Error('trio bag action unavailable at 3/3');await page.locator('[data-v7-sample]').nth(3).click();if(await page.locator('[data-replace-slot]').count()<1)throw new Error('replacement state missing when trio is full');await page.locator('[data-replace-slot]').first().click();await inspect(page,'discovery-trio');await page.close()});

await task('5-rate-after-try',async()=>{const page=await context.newPage();await page.goto(`${base}/discovery.html#after-try`);await settle(page);const card=page.locator('[data-feedback-card]').first();await card.locator('[data-sentiment="love"]').click();await card.locator('[data-feedback-tag="too-sweet"]').click();await card.locator('[data-save-feedback]').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('violet-sample-feedback-v1')||'{}'));if(!Object.keys(saved).length)throw new Error('feedback not persisted');if(!Object.values(saved)[0].tags.includes('too-sweet'))throw new Error('feedback reason tag not persisted');await inspect(page,'after-try-feedback');await page.close()});

await task('6-return-to-refined-recommendations',async()=>{const page=await context.newPage();await page.goto(`${base}/finder.html`);await settle(page);for(let i=0;i<9;i++){const next=page.locator('[data-next]');if(await next.count()===0)break;if(await next.isDisabled())throw new Error(`saved portrait did not prefill step ${i+1}`);await next.click();await page.waitForTimeout(60)}await page.waitForSelector('.portrait-results');const text=await page.locator('.results-heading').innerText();if(!/saved trial note/i.test(text))throw new Error('saved feedback is not disclosed in refined recommendations');const reasons=await page.locator('.result-why-block li').allInnerTexts();if(!reasons.some(x=>/feedback|sweet|love|liked/i.test(x)))throw new Error('feedback evidence not surfaced in recommendation reasons');await inspect(page,'portrait-refined');await page.close()});

for(const spec of [{name:'home',url:'/index.html'},{name:'checkout',url:'/checkout.html'},{name:'seller',url:'/seller.html'},{name:'admin',url:'/admin.html'}]){const page=await context.newPage();await page.goto(base+spec.url);await settle(page);await inspect(page,spec.name);await page.close()}

const p0=report.issues.filter(x=>x.severity==='P0').length,p1=report.issues.filter(x=>x.severity==='P1').length;report.status=p0===0&&p1===0&&report.tasks.every(t=>t.status==='passed')?'passed':'failed';fs.writeFileSync(path.join(out,'mobile-discovery-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,tasks:report.tasks,issues:report.issues},null,2));await browser.close();server.kill('SIGTERM');if(report.status!=='passed')process.exitCode=1;
