import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { chromium } from 'playwright';

const out=path.resolve(process.argv[2]||'artifacts/v4-full-qa');fs.mkdirSync(out,{recursive:true});
const port=4178,base=`http://127.0.0.1:${port}`;
const server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1'],{cwd:process.cwd(),stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitServer(){for(let i=0;i<50;i++){try{const r=await fetch(`${base}/index.html`,{cache:'no-store'});if(r.ok)return;}catch{}await sleep(200);}throw new Error('server not ready');}
async function settle(page){await page.evaluate(async()=>{document.querySelectorAll('img[loading="lazy"]').forEach(img=>img.loading='eager');const h=document.documentElement.scrollHeight,step=Math.max(500,Math.floor(innerHeight*.75));for(let y=0;y<h;y+=step){scrollTo(0,y);await new Promise(r=>setTimeout(r,75));}await Promise.all([...document.images].map(img=>img.decode?.().catch(()=>{})||Promise.resolve()));scrollTo(0,0);});await page.waitForTimeout(220);}
const report={status:'passed',threshold:94,viewport:{width:1440,height:1000},pages:[],journeys:[],pressure:[],issues:[]};
const issue=(page,severity,code,message)=>report.issues.push({page,severity,code,message});
function events(page){const consoleErrors=[],pageErrors=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>pageErrors.push(String(e)));return{consoleErrors,pageErrors};}
async function baseMetrics(page){return page.evaluate(()=>{const visible=el=>{if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};return{scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,h1Count:document.querySelectorAll('h1').length,v4:document.body.classList.contains('violet-v4'),nav:[...document.querySelectorAll('.nav-inner a')].map(a=>a.textContent.trim()),broken:[...document.images].filter(img=>visible(img)&&img.complete&&img.naturalWidth===0).map(img=>img.currentSrc||img.src),incomplete:[...document.images].filter(img=>visible(img)&&!img.complete).map(img=>img.currentSrc||img.src),v3Primary:!!document.querySelector('.v3-editorial-bridge,.pdp-v3,.fragrance-library-hero')};});}
function inspectBase(name,m,e){if(e.consoleErrors.length)issue(name,'P0','console-error',e.consoleErrors.join(' | '));if(e.pageErrors.length)issue(name,'P0','page-error',e.pageErrors.join(' | '));if(m.broken.length)issue(name,'P0','broken-image',m.broken.join(' | '));if(m.incomplete.length)issue(name,'P0','incomplete-image',m.incomplete.join(' | '));if(m.scrollWidth>m.clientWidth+2)issue(name,'P0','overflow',`${m.scrollWidth}>${m.clientWidth}`);if(m.h1Count!==1)issue(name,'P1','heading',`Expected one h1, got ${m.h1Count}`);if(!m.v4)issue(name,'P0','v4-runtime','V4 runtime class missing');if(!m.nav.includes('Fragrances')||!m.nav.includes('Houses')||!m.nav.includes('Discovery')||!m.nav.includes('Scent Portrait'))issue(name,'P1','navigation',`Task-led navigation missing: ${m.nav.join(', ')}`);if(m.v3Primary)issue(name,'P1','legacy-shell','Legacy V3 primary shell remains visible');}

await waitServer();const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,colorScheme:'light'});

const standard=[
 ['home','/index.html'],['library','/search.html?sample=1'],['pdp','/product.html?id=violette-03'],['discovery','/discovery.html'],['houses','/houses.html'],['house-maison-aster','/house.html?id=maison-aster']
];
for(const [name,url] of standard){const page=await context.newPage(),e=events(page);await page.goto(base+url,{waitUntil:'networkidle',timeout:45000});await settle(page);const m=await baseMetrics(page);inspectBase(name,m,e);
 if(name==='home'){const x=await page.evaluate(()=>({routes:document.querySelectorAll('.v4-route').length,houses:document.querySelectorAll('.v4-house-index a').length,feature:!!document.querySelector('.v4-home-hero')}));if(!x.feature||x.routes!==3||x.houses<4)issue(name,'P1','home-contract',JSON.stringify(x));}
 if(name==='library'){const x=await page.evaluate(()=>({cols:getComputedStyle(document.querySelector('.v4-object-grid')).gridTemplateColumns.split(' ').filter(Boolean).length,cards:document.querySelectorAll('.v4-object-card').length,interrupt:document.querySelectorAll('.v4-plp-interrupt').length,filters:!!document.querySelector('.v4-filter-rail'),chips:[...document.querySelectorAll('.chip')].map(x=>x.textContent.trim())}));if(x.cols!==3||x.cards<6||!x.filters||x.interrupt!==1)issue(name,'P1','library-contract',JSON.stringify(x));if(!x.chips.some(x=>x.toLowerCase().includes('trial')))issue(name,'P1','filter-state','Trial filter chip not visible');}
 if(name==='pdp'){const x=await page.evaluate(()=>({buying:!!document.querySelector('.v4-buying-desk'),sample:!!document.querySelector('[data-v4-add-sample]'),bottle:!!document.querySelector('[data-v4-add-bottle]'),story:!!document.querySelector('.v4-pdp-story')}));if(!x.buying||!x.sample||!x.bottle||!x.story)issue(name,'P1','pdp-contract',JSON.stringify(x));}
 if(name==='discovery'){const x=await page.evaluate(()=>({workspace:!!document.querySelector('.v4-discovery-workspace'),rows:document.querySelectorAll('.v4-sample-row').length,reality:document.body.textContent.includes('no sample fulfillment')||document.body.textContent.includes('representative')}));if(!x.workspace||x.rows<5||!x.reality)issue(name,'P1','discovery-contract',JSON.stringify(x));}
 if(name==='houses'){const rows=await page.locator('.v4-house-ledger-row').count();if(rows<5)issue(name,'P1','houses-index',`Expected >=5 houses, got ${rows}`);}
 if(name==='house-maison-aster'){const x=await page.evaluate(()=>({hero:!!document.querySelector('.v4-house-hero'),objects:document.querySelectorAll('.v4-house-object').length,fictional:document.body.textContent.toLowerCase().includes('fictional')}));if(!x.hero||x.objects<1||!x.fictional)issue(name,'P1','house-contract',JSON.stringify(x));}
 await page.screenshot({path:path.join(out,`${name}-1440.png`),fullPage:true});report.pages.push({name,url,metrics:m});await page.close();}

// Scent Portrait: complete all four reversible decisions and verify handoff to Discovery.
{
 const page=await context.newPage(),e=events(page);await page.goto(base+'/finder.html',{waitUntil:'networkidle',timeout:45000});
 for(let step=0;step<4;step++){await page.locator('[data-value]').first().click();await page.locator('[data-next]').click();}
 await page.waitForSelector('.portrait-results');await settle(page);const m=await baseMetrics(page);inspectBase('finder-results',m,e);const x=await page.evaluate(()=>({cards:document.querySelectorAll('.portrait-result').length,discoveryHref:document.querySelector('.portrait-discovery a')?.getAttribute('href'),handoff:!!document.querySelector('.v4-finder-handoff'),truth:document.body.textContent.includes('deterministic recommendation')}));if(x.cards!==3||x.discoveryHref!=='discovery.html'||!x.handoff||!x.truth)issue('finder-results','P1','finder-contract',JSON.stringify(x));await page.screenshot({path:path.join(out,'finder-results-1440.png'),fullPage:true});report.pages.push({name:'finder-results',url:'/finder.html',metrics:m,contract:x});await page.close();
}

// Discovery state: enforce three-item cap, persistence and removal.
{
 const page=await context.newPage(),e=events(page);await page.goto(base+'/discovery.html',{waitUntil:'networkidle',timeout:45000});await page.evaluate(()=>localStorage.removeItem('violet-discovery-trio-v1'));await page.reload({waitUntil:'networkidle'});for(let i=0;i<3;i++){const b=page.locator('[data-v4-sample-choice]:not([disabled])').first();await b.click();}let trio=await page.evaluate(()=>JSON.parse(localStorage.getItem('violet-discovery-trio-v1')||'[]'));if(trio.length!==3)issue('discovery-state','P0','trio-cap',`Expected 3, got ${trio.length}`);if(await page.locator('[data-v4-sample-choice][disabled]').count()<1)issue('discovery-state','P1','trio-disabled','Fourth choice is not disabled');await page.reload({waitUntil:'networkidle'});trio=await page.evaluate(()=>JSON.parse(localStorage.getItem('violet-discovery-trio-v1')||'[]'));if(trio.length!==3)issue('discovery-state','P0','trio-persistence',`Expected persisted 3, got ${trio.length}`);await page.locator('[data-v4-remove-sample]').first().click();trio=await page.evaluate(()=>JSON.parse(localStorage.getItem('violet-discovery-trio-v1')||'[]'));if(trio.length!==2)issue('discovery-state','P1','trio-recovery',`Expected removal to leave 2, got ${trio.length}`);report.journeys.push({name:'discovery-trio',selectedAfterRemoval:trio.length});await page.close();
}

// PDP actions feed the same local trial/cart contracts.
{
 const page=await context.newPage();await page.goto(base+'/product.html?id=violette-03',{waitUntil:'networkidle'});await page.evaluate(()=>{localStorage.removeItem('violet-discovery-trio-v1');localStorage.setItem('violet-marketplace-cart-v1','[]')});await page.reload({waitUntil:'networkidle'});await page.locator('[data-v4-add-sample]').click();await page.locator('[data-v4-add-bottle]').click();const state=await page.evaluate(()=>({trio:JSON.parse(localStorage.getItem('violet-discovery-trio-v1')||'[]'),cart:JSON.parse(localStorage.getItem('violet-marketplace-cart-v1')||'[]')}));if(state.trio.length!==1||!state.cart.some(x=>x.id==='violette-03'))issue('pdp-actions','P0','pdp-state',JSON.stringify(state));report.journeys.push({name:'pdp-to-trio-and-bag',...state});await page.close();
}

// Utility journey with seeded cart and truthful simulated checkout/confirmation.
await (async()=>{const seed=await context.newPage();await seed.goto(base+'/index.html');await seed.evaluate(()=>{localStorage.setItem('violet-marketplace-cart-v1',JSON.stringify([{id:'violette-03',qty:1}]));localStorage.setItem('violet-marketplace-last-order',JSON.stringify({code:'VIOLET-QA-001',total:3890000}));});await seed.close();})();
for(const [name,url] of [['bag','/cart.html'],['checkout','/checkout.html'],['confirmation','/order-success.html']]){const page=await context.newPage(),e=events(page);await page.goto(base+url,{waitUntil:'networkidle',timeout:45000});await settle(page);const m=await baseMetrics(page);inspectBase(name,m,e);if(name==='bag'){if(await page.locator('.cart-item').count()<1)issue(name,'P1','bag-state','Seeded cart item not rendered');}if(name==='checkout'){const x=await page.evaluate(()=>({labels:document.querySelectorAll('label').length,required:document.querySelectorAll('[required]').length,reality:document.body.textContent.includes('do not process a real transaction')}));if(x.labels<5||x.required<5||!x.reality)issue(name,'P1','checkout-contract',JSON.stringify(x));}if(name==='confirmation'){const text=(await page.textContent('body')).toLowerCase();if(!text.includes('prototype')||text.includes('on its way'))issue(name,'P1','confirmation-reality','Confirmation must stay explicitly simulated/browser-local');}await page.screenshot({path:path.join(out,`${name}-1440.png`),fullPage:true});report.pages.push({name,url,metrics:m});await page.close();}

for(const width of [1280,1600]){for(const [name,url] of [['home','/index.html'],['library','/search.html?sample=1'],['pdp','/product.html?id=violette-03'],['discovery','/discovery.html'],['houses','/houses.html'],['finder','/finder.html'],['checkout','/checkout.html']]){const page=await context.newPage();await page.setViewportSize({width,height:1000});await page.goto(base+url,{waitUntil:'networkidle',timeout:45000});await settle(page);const m=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,broken:[...document.images].filter(img=>img.complete&&img.naturalWidth===0).length}));if(m.scrollWidth>m.clientWidth+2)issue(`${name}-${width}`,'P0','pressure-overflow',`${m.scrollWidth}>${m.clientWidth}`);if(m.broken)issue(`${name}-${width}`,'P0','pressure-media',`${m.broken} broken images`);report.pressure.push({name,width,...m});await page.close();}}

const p0=report.issues.filter(x=>x.severity==='P0').length,p1=report.issues.filter(x=>x.severity==='P1').length,p2=report.issues.filter(x=>x.severity==='P2').length;report.score=Math.max(0,100-p0*20-p1*7-p2*2);report.status=report.score>=report.threshold&&p0===0&&p1===0?'passed':'failed';fs.writeFileSync(path.join(out,'v4-full-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,score:report.score,p0,p1,p2,issues:report.issues},null,2));await browser.close();server.kill('SIGTERM');if(report.status!=='passed')process.exitCode=1;
