import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { chromium } from 'playwright';

const out=path.resolve(process.argv[2]||'artifacts/v4-representative-qa'); fs.mkdirSync(out,{recursive:true});
const port=4176, base=`http://127.0.0.1:${port}`;
const server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1'],{cwd:process.cwd(),stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitServer(){for(let i=0;i<40;i++){try{const r=await fetch(`${base}/index.html`,{cache:'no-store'});if(r.ok)return;}catch{}await sleep(250);}throw new Error('server not ready');}
async function settle(page){await page.evaluate(async()=>{document.querySelectorAll('img[loading="lazy"]').forEach(img=>img.loading='eager');document.documentElement.style.scrollBehavior='auto';const h=document.documentElement.scrollHeight,step=Math.max(500,Math.floor(innerHeight*.75));for(let y=0;y<h;y+=step){scrollTo(0,y);await new Promise(r=>setTimeout(r,90));}await Promise.all([...document.images].map(img=>img.decode?.().catch(()=>{})||Promise.resolve()));scrollTo(0,0);});await page.waitForTimeout(250);}
const report={status:'passed',threshold:94,viewport:{width:1440,height:1000},locale:'vi',pages:[],pressure:[],issues:[]};
const issue=(page,severity,code,message)=>report.issues.push({page,severity,code,message});
await waitServer(); const browser=await chromium.launch({headless:true}); const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,colorScheme:'light'});

const specs=[
 {name:'home-v4',path:'/index.html',kind:'home'},
 {name:'library-v4',path:'/search.html?sample=1',kind:'library'},
 {name:'pdp-v4',path:'/product.html?id=violette-03',kind:'product'},
 {name:'discovery-v4',path:'/discovery.html',kind:'discovery'}
];
for(const spec of specs){
 const page=await context.newPage(); const consoleErrors=[],pageErrors=[]; page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>pageErrors.push(String(e)));
 await page.goto(base+spec.path,{waitUntil:'networkidle',timeout:45000}); await settle(page);
 const metrics=await page.evaluate(kind=>{const visible=el=>{if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};const doc=document.documentElement;return {kind,lang:document.documentElement.lang,scrollWidth:doc.scrollWidth,clientWidth:doc.clientWidth,h1Count:document.querySelectorAll('h1').length,v4:document.body.classList.contains('violet-v4'),nav:[...document.querySelectorAll('.nav-inner a')].map(a=>a.textContent.trim()),broken:[...document.images].filter(img=>visible(img)&&img.complete&&img.naturalWidth===0).map(img=>img.currentSrc||img.src),incomplete:[...document.images].filter(img=>visible(img)&&!img.complete).map(img=>img.currentSrc||img.src),oldV3:!!document.querySelector('.v3-editorial-bridge,.pdp-v3,.fragrance-library-hero'),homeFeature:visible(document.querySelector('.v4-home-hero')),routeCount:document.querySelectorAll('.v4-route').length,houseRows:document.querySelectorAll('.v4-house-index a').length,filter:visible(document.querySelector('.v4-filter-rail')),gridCols:document.querySelector('.v4-object-grid')?getComputedStyle(document.querySelector('.v4-object-grid')).gridTemplateColumns.split(' ').filter(Boolean).length:0,interrupt:visible(document.querySelector('.v4-plp-interrupt')),buying:visible(document.querySelector('.v4-buying-desk')),sampleAction:visible(document.querySelector('[data-v4-add-sample]')),bottleAction:visible(document.querySelector('[data-v4-add-bottle]')),discoveryWorkspace:visible(document.querySelector('.v4-discovery-workspace')),sampleRows:document.querySelectorAll('.v4-sample-row').length};},spec.kind);
 if(consoleErrors.length)issue(spec.name,'P0','console-error',consoleErrors.join(' | '));if(pageErrors.length)issue(spec.name,'P0','page-error',pageErrors.join(' | '));if(metrics.broken.length)issue(spec.name,'P0','broken-image',metrics.broken.join(' | '));if(metrics.incomplete.length)issue(spec.name,'P0','incomplete-image',metrics.incomplete.join(' | '));if(metrics.scrollWidth>metrics.clientWidth+2)issue(spec.name,'P0','overflow',`${metrics.scrollWidth}>${metrics.clientWidth}`);if(metrics.h1Count!==1)issue(spec.name,'P1','heading',`Expected one h1, got ${metrics.h1Count}`);if(metrics.lang!=='vi')issue(spec.name,'P1','locale',`Expected vi locale, got ${metrics.lang}`);if(!metrics.v4)issue(spec.name,'P0','v4-contract','V4 runtime class missing');if(!metrics.nav.includes('Nhà hương')||!metrics.nav.includes('Khám phá')||!metrics.nav.includes('Chân dung mùi hương'))issue(spec.name,'P1','nav','Thiếu điều hướng V4 theo nhiệm vụ bằng tiếng Việt');if(metrics.oldV3)issue(spec.name,'P1','structural-delta','Legacy V3 primary shell is still present');
 if(spec.kind==='home'){if(!metrics.homeFeature||metrics.routeCount!==3||metrics.houseRows<4)issue(spec.name,'P1','home-structure',JSON.stringify(metrics));}
 if(spec.kind==='library'){if(!metrics.filter||metrics.gridCols!==3)issue(spec.name,'P1','library-structure',JSON.stringify(metrics));}
 if(spec.kind==='product'){if(!metrics.buying||!metrics.sampleAction||!metrics.bottleAction)issue(spec.name,'P1','buying-desk',JSON.stringify(metrics));}
 if(spec.kind==='discovery'){
   if(!metrics.discoveryWorkspace||metrics.sampleRows<5)issue(spec.name,'P1','discovery-structure',JSON.stringify(metrics));
   const buttons=page.locator('[data-v4-sample-choice]:not([disabled])'); for(let i=0;i<3;i++)await buttons.nth(i).click(); const trio=await page.evaluate(()=>JSON.parse(localStorage.getItem('violet-discovery-trio-v1')||'[]')); if(trio.length!==3)issue(spec.name,'P0','trio-state',`Expected 3 selected, got ${trio.length}`); const disabled=await page.locator('[data-v4-sample-choice][disabled]').count(); if(disabled<1)issue(spec.name,'P1','trio-capacity','Unselected sample choices should disable at 3/3'); await page.reload({waitUntil:'networkidle'}); const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('violet-discovery-trio-v1')||'[]')); if(persisted.length!==3)issue(spec.name,'P0','trio-persistence','Trio did not persist');
 }
 await page.screenshot({path:path.join(out,`${spec.name}-1440.png`),fullPage:true}); report.pages.push({name:spec.name,path:spec.path,metrics,consoleErrors,pageErrors}); await page.close();
}
for(const width of [1280,1600]){for(const item of [{name:'home',path:'/index.html'},{name:'pdp',path:'/product.html?id=violette-03'},{name:'discovery',path:'/discovery.html'}]){const page=await context.newPage();await page.setViewportSize({width,height:1000});await page.goto(base+item.path,{waitUntil:'networkidle',timeout:45000});await settle(page);const m=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,broken:[...document.images].filter(img=>img.complete&&img.naturalWidth===0).length}));if(m.scrollWidth>m.clientWidth+2)issue(`${item.name}-${width}`,'P0','pressure-overflow',`${m.scrollWidth}>${m.clientWidth}`);if(m.broken)issue(`${item.name}-${width}`,'P0','pressure-media',`${m.broken} broken images`);await page.screenshot({path:path.join(out,`${item.name}-${width}-top.png`),fullPage:false});report.pressure.push({page:item.name,width,...m});await page.close();}}
const p0=report.issues.filter(x=>x.severity==='P0').length,p1=report.issues.filter(x=>x.severity==='P1').length;report.score=Math.max(0,100-p0*20-p1*7);report.status=report.score>=report.threshold&&p0===0&&p1===0?'passed':'failed';fs.writeFileSync(path.join(out,'v4-representative-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,score:report.score,issues:report.issues},null,2));await browser.close();server.kill('SIGTERM');if(report.status!=='passed')process.exitCode=1;
